Added documentation
Sharingang/Sharingang-Android pull request #217
Opened 2021-05-11 18:07 UTC by Superdoude1999

Added most of missing documentation (didn't do utils folder).
Also changed the title of the sold item list fragment.

2021-05-12 14:37 UTC, v1ruso approved these changes

2021-05-13 17:42 UTC, lumapools requested changes
Thank you for documenting! Please could you see my requested changes? I don't think you need `[ ]` around `@param`s.
Also, instead of writing `Function that does this and that` for the documentation, it is better practice to write `Does this and that`. Same for classes , i.e. don't specify `Class that represents ...` but just `Represents ...`. Also, make sure to add `@property` for the fields contained by a Class.

2021-05-13 17:42 UTC, lumapools commented on app/src/main/java/com/example/sharingang/AbstractFirestoreStore.kt
> +     * @param[id] The id of the element to remove.
```suggestion
     * @param id The id of the element to remove.
```

2021-05-13 17:42 UTC, lumapools commented on app/src/main/java/com/example/sharingang/DateConverter.kt
> +     * @param[timestamp]
```suggestion
     * @param timestamp
```

2021-05-13 17:42 UTC, lumapools commented on app/src/main/java/com/example/sharingang/ListConverter.kt
> +     * @param[list] List of Strings to convert.
```suggestion
     * @param list List of Strings to convert.
```

2021-05-13 17:42 UTC, lumapools commented on app/src/main/java/com/example/sharingang/items/ItemDao.kt
> +     * @param[userId] The id of the user.
```suggestion
     * @param userId The id of the user.
```

2021-05-13 17:42 UTC, lumapools commented on app/src/main/java/com/example/sharingang/items/ItemDao.kt
> +     * @param[items] List aof new items.
```suggestion
     * @param items List of new items.
```

2021-05-13 17:42 UTC, lumapools commented on app/src/main/java/com/example/sharingang/users/UserDao.kt
> +     * @param[users] List of users to add.
```suggestion
     * @param users List of users to add.
```

2021-05-13 17:42 UTC, lumapools commented on app/src/main/java/com/example/sharingang/users/UserDao.kt
> +     * @param[users] List of users to replace with.
```suggestion
     * @param users List of users to replace with.
```

2021-05-14 01:57 UTC, lumapools approved these changes
Added some suggestions for some missed `@property`s. Good work overall!

2021-05-14 01:57 UTC, lumapools commented on app/src/main/java/com/example/sharingang/AbstractFirestoreStore.kt
> + */
```suggestion
/**
 * Abstract class to implement basic database usage.
 * @param[T] Type of element to use for database.
 * @property collectionName The name of the collection
 * @property typeClass Class with type T
 * @property firestore instance of FirebaseFirestore
 */
```

2021-05-14 01:57 UTC, lumapools commented on app/src/main/java/com/example/sharingang/items/CachedItemRepository.kt
> + */
```suggestion
/**
 * Class to implement an ItemRepository in cache.
 * @property itemDao used item data access object
 * @property store used ItemStore
 */
```

2021-05-14 01:57 UTC, lumapools commented on app/src/main/java/com/example/sharingang/items/ItemsAdapter.kt
> +     */
```suggestion
    /**
     * Recycler view to represent a single item.
     * @property binding item view binding
     */
```

2021-05-14 01:57 UTC, lumapools commented on app/src/main/java/com/example/sharingang/users/FirestoreCurrentUserProvider.kt
> + */
```suggestion
/**
 * Class used to retrieve the current signed in user.
 * @property auth the authenticator to use
 */
```

2021-05-14 06:52 UTC, merged